[package]
name = "stabby-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
proc-macro2 = "1.0"
proc-macro-crate = "1.3"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[lib]
proc-macro = true
